# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: remitano 0.4.0 ruby lib

Gem::Specification.new do |spec|
  spec.name = "remitano"
  spec.version = "0.0.1"

  spec.authors = ["Phuong Gia Su"]
  spec.description = "Ruby API for use with remitano."
  spec.email = "phuongnd08@gmail.com"
  spec.files = `git ls-files -z`.split("\x0")
  spec.homepage = "http://github.com/phuongnd08/remitano-ruby"
  spec.licenses = ["MIT"]
  spec.require_paths = ["lib"]
  spec.rubygems_version = "2.1.11"
  spec.summary = "Remitano Ruby API"

  spec.add_runtime_dependency("activemodel", [">= 3.1"])
  spec.add_runtime_dependency("activesupport", [">= 3.1"])
  spec.add_runtime_dependency("rest_client", [">= 1.7.3"])
  spec.add_runtime_dependency("ruby-hmac", ["= 0.4.0"])
  spec.add_development_dependency("rspec", [">= 0"])
  spec.add_development_dependency("rdoc", ["~> 3.12"])
  spec.add_development_dependency("bundler")
  spec.add_development_dependency("jeweler", ["~> 1.8.4"])
  spec.add_development_dependency("dotenv", ["~> 2.0.0"])
  spec.add_development_dependency("vcr", ["~> 2.6.0"])
  spec.add_development_dependency("webmock", ["~> 1.13.0"])
end

